# Linter Options
options:
    merge-default-rules: false

# Rule Configuration
rules:
    brace-style:
        - 2
        -
            style: 'stroustrup'
    clean-import-paths: 2
    extends-before-declarations: 2
    extends-before-mixins: 2
    final-newline: 2
    indentation:
        - 2
        -
            size: 4
    leading-zero:
        - 2
        -
            include: true
    no-css-comments: 1
    no-debug: 2
    no-empty-rulesets: 2
    no-ids: 1
    no-important: 1
    no-invalid-hex: 2
    no-misspelled-properties: 2
    no-vendor-prefixes: 1
    no-duplicate-properties:
        - 2
        -
            exclude:
                - src
                - transform
    one-declaration-per-line: 1
    single-line-per-selector: 2
    attribute-quotes: 2
    url-quotes: 2
    quotes:
        - 1
        -
            style: 'single'
    space-after-colon: 2
    space-after-comma: 2
    space-around-operator: 2
    space-before-bang: 2
    space-before-brace: 2
    trailing-semicolon: 2
    zero-unit: 2
